### ISSUE TITLE
[Feature] Exported Content In Error Event

### ISSUE THREAD

**Issue by NeoYaBoi** [sern-handler/handler#106]
Request a new feature!
---
### Is your proposal related to a problem?
No

### Describe the solution you'd like
I think it would be pretty cool and beneficial to be able to access module exported content and information when a error occurs. This would be via the error event within the sern event type. This would allow us to create crash dumps for example that can return error solutions to the user via a new exported member.

### Describe alternatives you've considered
I cannot think of any other solutions while remaining using the sern handler

### Additional context
None

**Comment by jacoobes** [comment]
#115 

This pull request will add ( module | undefined ) info to error events.
