### ISSUE TITLE
[Feature] Database Support

### ISSUE THREAD

**Issue by Benzo-Fury** [sern-handler/handler#107]
Request a new feature!
---
### Is your proposal related to a problem?
No

### Describe the solution you'd like
Sern should have capability/support for a database connection. Possibly something you specify in your main file. Sern would automatically connect to the URI and enable devs to create bots with databases without having to manually do it themselves.

### Describe alternatives you've considered
Manually connecting to database every time bot starts.

### Additional context
None

**Comment by jacoobes** [comment]
Could this not be done in a few lines? I don't see why we would need to add this.

**Comment by Murtatrxx** [comment]
We might add database templates soon. But we are not clear.

**Comment by NeoYaBoi** [comment]
> Could this not be done in a few lines? I don't see why we would need to add this.

Yes, but having it built into Sern would also open up a lot of potential for plugins. It would allow plugin devs to have information stored via sern. Doing it manually wouldn't be easy (in plugins).

**Comment by jacoobes** [comment]
Will be thought about. Thanks for the request!

**Comment by jacoobes** [comment]
Hello, an update, this issue will be probably be resolved in the next update!

**Comment by jacoobes** [comment]
2.0 resolves this.
You can connect your database connection to sern and use it anywhere in your project
