### ISSUE TITLE
[BUG] Error Event Bug

### ISSUE THREAD

**Issue by NeoYaBoi** [sern-handler/handler#114]
**Describe the bug**
Error event stops entire bot from running (does not exit process).
E.G: I run ping command, it has error, error event runs, I attempt to run another command, command does not run.

**To Reproduce**
1. Create a error event
2. Create a error in a cmd
3. Run command
4. See error event run
5. Run another command that does not have error
6. See Bug

**Expected behavior**
The bot would continue to run as normal

**Versioning**
NodeJS version: 16.17.0
DiscordJS version: 14.2.0
SernHandler version: 1.0.1

**Additional context**
Sorry if I didn't explain this very well

**Comment by jacoobes** [comment]
#115
