### ISSUE TITLE
[BUG] sern handler fails to resolve typings for moduleResolution: "nodenext"

### ISSUE THREAD

**Issue by jacoobes** [sern-handler/handler#284]
Building with module resolution 'nodenext' fails with this error
```sh
Could not find a declaration file for module '@sern/handler'. 'C:/Users/~/OneDrive/Desktop/Projects/~/node_modules/@sern/handler/dist/esm/index.mjs' implicitly has an 'any' type.
  There are types at 'C:/Users/~/OneDrive/Desktop/Projects/~/node_modules/@sern/handler/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@sern/handler' library may need to update its package.json or typings

```

**To Reproduce**
1. Create a new typescript project with `sern init`
2. switch to an esm configuration
3. module resolution in tsconfig.json should be 'nodenext'

**Expected behavior**
Typings should work

**Screenshots**

**Versioning**
NodeJS version: 17.6.0
DiscordJS version: 14.9.1
SernHandler version: 2.6.1
Channel: (e.g. beta)

**Additional context**

**Comment by Murtatrxx** [comment]
Can confirm Evo

**Comment by jacoobes** [comment]
yeah, this bug works with  moduleResolution work with "node", however, wondering what could be the issue for a "nodenext" project.

**Comment by jacoobes** [comment]
Found the issue. will be fixed in v3 
[#molszanski/iti/37](https://github.com/molszanski/iti/issues/37)
#294
