### ISSUE TITLE
[BUG] Buttons not registering

### ISSUE THREAD

**Issue by needhamgary** [sern-handler/handler#303]
**Describe the bug**
My buttons are not registering on init.

**To Reproduce**
1. Create a button in an event or command and send to the channel.
2. Create a Button command with the custom id as the name like normal.
3. Click the button sent in discord. Returns "interaction failed" with no errors.

**Expected behavior**
My button is set to console.log("button") and nothing happens

**Screenshots**
![image](https://github.com/sern-handler/handler/assets/23411307/8895802e-07ef-4338-bb71-250ac5d7adb7)
![image](https://github.com/sern-handler/handler/assets/23411307/911f74f8-4e1f-4df6-a7e4-a510b0f0c0f1)

**Versioning**
NodeJS version: 20.2.0
DiscordJS version: 14.11^
SernHandler version: 3.0.0rc4 
Channel: alpha

**Additional context**
Additional information available in sern Community discord server

**Comment by jacoobes** [comment]
fixed in recent push to alpha (rc5)
#294
