### ISSUE TITLE
[BUG] Defective select menus.

### ISSUE THREAD

**Issue by needhamgary** [sern-handler/handler#304]
**Describe the bug**
CommandType ChannelSelect and RoleSelect are not working at all, just returning undefined.

**To Reproduce**
1. create channel select menu or role select menu command
2. listen for them in commandModule
3. use the select menu
4. console returns undefined 

**Expected behavior**
log the string "role-menu" when 

**Screenshots**
commandModule
![image](https://github.com/sern-handler/handler/assets/23411307/05a28747-a792-4b0e-b7ea-42ba026fc513)
creating the menu
![image](https://github.com/sern-handler/handler/assets/23411307/b9e52e16-ba2b-4fb5-b467-bfbdb9d2751b)
selecting a role or a channel just returns undefined in the console

**Versioning**
NodeJS version: 20.2.0
DiscordJS version: 14.11.0
SernHandler version: 3.0.0rc5
Channel: alpha

**Comment by jacoobes** [comment]
Fixed in 3.0.0rc6. #294 
Problem was misaligned command types
