### ISSUE TITLE
[BUG] You provided 'undefined' where a stream was expected. You can provide an Observable, Promise, ReadableStream, Array, AsyncIterable, or Iterable

### ISSUE THREAD

**Issue by jacoobes** [sern-handler/handler#86]
Whenever a command module has a non asynchronous function that does not return anything, this rxjs error occurs

**Expected behavior**
It should not crash on this.

**Screenshots**

**Versioning**
NodeJS version: 16.14.0
DiscordJS version: ^14.0.0-dev.1657757514-fe34f48
SernHandler version: 1.1.0-beta
Channel: (e.g. beta)

**Additional context**

**Comment by Murtatrxx** [comment]
🤨

**Comment by jacoobes** [comment]
Had to document this error

**Comment by jacoobes** [comment]
Fixed in a new patch

**Comment by EvolutionX-10** [comment]
GG
